### ISSUE TITLE
Repository https://github.com/bizzehdee/picopad_base/ doesn't exist ?

### ISSUE THREAD

**Issue by tomasvladik** [tvecera/picopad-playground#2]
https://github.com/tvecera/picopad-playground/blob/56549359c6d9f371305089e2c280a232eede245a/picopad-sdk/picopad-gb/picopad_base_import.cmake#L30

I'm getting 404 for the repo https://github.com/bizzehdee/picopad_base/

What is wrong with it?

**Comment by tvecera** [comment]
Fixed by pull request from #4. In the future I want to remove submodules, it's causing problems for most users.
