### ISSUE TITLE
Using SSH to clone submodules is problematic for anonymous user

### ISSUE THREAD

**Issue by tomasvladik** [tvecera/picopad-playground#3]
https://github.com/tvecera/picopad-playground/blob/56549359c6d9f371305089e2c280a232eede245a/.gitmodules#L9

Using SSH access to GitHub requires user to have account and properly configured SSH keys.
Something hard to explain to common user, who want just to build his ROM for PicoPad. 
He or she follows instruction to clone with submodules and receive ["Error: Permission denied (publickey)"](https://docs.github.com/en/authentication/troubleshooting-ssh/error-permission-denied-publickey)
It makes also the some trouble, if you make Dockerfile to automatize the task.

I think that reference to 2 repos from https://github.com/tuupola/ could be switch to https with no issue

**Comment by tomasvladik** [comment]
I can't create branch/pullrequest  ..... so it could be modified with no issue to this:

[submodule "picopad-sdk/picopad-base/src/vendor/hagl_hal"]
	path = picopad-sdk/picopad-base/src/vendor/hagl_hal
	url = https://github.com/tuupola/hagl_pico_mipi.git
[submodule "picopad-sdk/picopad-base/src/vendor/hagl"]
	path = picopad-sdk/picopad-base/src/vendor/hagl
	url = https://github.com/tuupola/hagl.git

**Comment by tvecera** [comment]
Fixed by pull request from #4.
