### ISSUE TITLE
Unable to build gb emulator

### ISSUE THREAD

**Issue by Gabbajoe** [tvecera/picopad-playground#4]
Hi I tried to build the gameboy emulator but I'm unable o build.
it looks like the picopad-base is not complete to build.

`nils@flunder:~/picopad/picopad-playground/picopad-sdk/picopad-gb$ cmake CMakeLists.txt 
PICO_SDK_PATH is /home/nils/picopad/picopad-playground/pico-sdk
PICO platform is rp2040.
Build type is Release
PICO target board is pico.
Using board configuration from /home/nils/picopad/picopad-playground/pico-sdk/src/boards/include/boards/pico.h
TinyUSB available at /home/nils/picopad/picopad-playground/pico-sdk/lib/tinyusb/src/portable/raspberrypi/rp2040; enabling build support for USB.
BTstack available at /home/nils/picopad/picopad-playground/pico-sdk/lib/btstack
cyw43-driver available at /home/nils/picopad/picopad-playground/pico-sdk/lib/cyw43-driver
Pico W Bluetooth build support available.
lwIP available at /home/nils/picopad/picopad-playground/pico-sdk/lib/lwip
mbedtls available at /home/nils/picopad/picopad-playground/pico-sdk/lib/mbedtls
CMake Error at /home/nils/picopad/picopad-playground/picopad-sdk/picopad-base/src/vendor/CMakeLists.txt:1 (add_subdirectory):
  The source directory

    /home/nils/picopad/picopad-playground/picopad-sdk/picopad-base/src/vendor/pico-onewire

  does not contain a CMakeLists.txt file.

CMake Error at /home/nils/picopad/picopad-playground/picopad-sdk/picopad-base/src/vendor/CMakeLists.txt:2 (add_subdirectory):
  The source directory

    /home/nils/picopad/picopad-playground/picopad-sdk/picopad-base/src/vendor/hagl

  does not contain a CMakeLists.txt file.

CMake Error at /home/nils/picopad/picopad-playground/picopad-sdk/picopad-base/src/vendor/CMakeLists.txt:3 (add_subdirectory):
  The source directory

    /home/nils/picopad/picopad-playground/picopad-sdk/picopad-base/src/vendor/hagl_hal

  does not contain a CMakeLists.txt file.

-- Configuring incomplete, errors occurred!
See also "/home/nils/picopad/picopad-playground/picopad-sdk/picopad-gb/CMakeFiles/CMakeOutput.log".
See also "/home/nils/picopad/picopad-playground/picopad-sdk/picopad-gb/CMakeFiles/CMakeError.log".
`

**Comment by Gabbajoe** [comment]
I found https://github.com/adamboardman/pico-onewire and https://github.com/tuupola/hagl 

For  hagl_hal I tried using https://github.com/saawsm/hagl_pico_mipi
so far I get now no error but nothing is build:

`
nils@flunder:~/picopad/picopad-playground/picopad-sdk/picopad-gb$ cmake CMakeLists.txt 
PICO_SDK_PATH is /home/nils/picopad/picopad-playground/pico-sdk
PICO platform is rp2040.
Build type is Release
PICO target board is pico.
Using board configuration from /home/nils/picopad/picopad-playground/pico-sdk/src/boards/include/boards/pico.h
TinyUSB available at /home/nils/picopad/picopad-playground/pico-sdk/lib/tinyusb/src/portable/raspberrypi/rp2040; enabling build support for USB.
BTstack available at /home/nils/picopad/picopad-playground/pico-sdk/lib/btstack
cyw43-driver available at /home/nils/picopad/picopad-playground/pico-sdk/lib/cyw43-driver
Pico W Bluetooth build support available.
lwIP available at /home/nils/picopad/picopad-playground/pico-sdk/lib/lwip
mbedtls available at /home/nils/picopad/picopad-playground/pico-sdk/lib/mbedtls
-- Configuring done
-- Generating done
-- Build files have been written to: /home/nils/picopad/picopad-playground/picopad-sdk/picopad-gb
nils@flunder:~/picopad/picopad-playground/picopad-sdk/picopad-gb$ ls -l build/
total 0

`

**Comment by Gabbajoe** [comment]
oh wow I feel dump a siple make afterwards did it ...

nils@flunder:~/picopad/picopad-playground/picopad-sdk/picopad-gb$ make
[  1%] Building ASM object pico-sdk/src/rp2_common/boot_stage2/CMakeFiles/bs2_default.dir/compile_time_choice.S.obj
[  2%] Linking ASM executable bs2_default.elf
[  2%] Built target bs2_default
[  3%] Generating bs2_default.bin
[  4%] Generating bs2_default_padded_checksummed.S
[  4%] Built target bs2_default_padded_checksummed_asm
[  5%] Building C object CMakeFiles/picopad-gb.dir/vendor/minigb_apu/minigb_apu.c.obj
[  6%] Building C object CMakeFiles/picopad-gb.dir/src/rom.c.obj
[  7%] Building CXX object CMakeFiles/picopad-gb.dir/src/main.cpp.obj
[  8%] Building C object CMakeFiles/picopad-gb.dir/home/nils/picopad/picopad-playground/pico-sdk/src/rp2_common/pico_stdlib/stdlib.c.obj
[  9%] Building C object CMakeFiles/picopad-gb.dir/home/nils/picopad/picopad-playground/pico-sdk/src/rp2_common/hardware_gpio/gpio.c.obj
[ 10%] Building C object CMakeFiles/picopad-gb.dir/home/nils/picopad/picopad-playground/pico-sdk/src/rp2_common/pico_platform/platform.c.obj
[ 11%] Building C object CMakeFiles/picopad-gb.dir/home/nils/picopad/picopad-playground/pico-sdk/src/rp2_common/hardware_claim/claim.c.obj
[ 12%] Building C object CMakeFiles/picopad-gb.dir/home/nils/picopad/picopad-playground/pico-sdk/src/rp2_common/hardware_sync/sync.c.obj
[ 13%] Building C object CMakeFiles/picopad-gb.dir/home/nils/picopad/picopad-playground/pico-sdk/src/rp2_common/hardware_irq/irq.c.obj
[ 14%] Building ASM object CMakeFiles/picopad-gb.dir/home/nils/picopad/picopad-playground/pico-sdk/src/rp2_common/hardware_irq/irq_handler_chain.S.obj
[ 15%] Building C object CMakeFiles/picopad-gb.dir/home/nils/picopad/picopad-playground/pico-sdk/src/common/pico_sync/sem.c.obj
[ 16%] Building C object CMakeFiles/picopad-gb.dir/home/nils/picopad/picopad-playground/pico-sdk/src/common/pico_sync/lock_core.c.obj
[ 17%] Building C object CMakeFiles/picopad-gb.dir/home/nils/picopad/picopad-playground/pico-sdk/src/common/pico_sync/mutex.c.obj
[ 18%] Building C object CMakeFiles/picopad-gb.dir/home/nils/picopad/picopad-playground/pico-sdk/src/common/pico_sync/critical_section.c.obj
[ 19%] Building C object CMakeFiles/picopad-gb.dir/home/nils/picopad/picopad-playground/pico-sdk/src/common/pico_time/time.c.obj
[ 20%] Building C object CMakeFiles/picopad-gb.dir/home/nils/picopad/picopad-playground/pico-sdk/src/common/pico_time/timeout_helper.c.obj
[ 21%] Building C object CMakeFiles/picopad-gb.dir/home/nils/picopad/picopad-playground/pico-sdk/src/rp2_common/hardware_timer/timer.c.obj
[ 22%] Building C object CMakeFiles/picopad-gb.dir/home/nils/picopad/picopad-playground/pico-sdk/src/common/pico_util/datetime.c.obj
[ 23%] Building C object CMakeFiles/picopad-gb.dir/home/nils/picopad/picopad-playground/pico-sdk/src/common/pico_util/pheap.c.obj
[ 24%] Building C object CMakeFiles/picopad-gb.dir/home/nils/picopad/picopad-playground/pico-sdk/src/common/pico_util/queue.c.obj
[ 25%] Building C object CMakeFiles/picopad-gb.dir/home/nils/picopad/picopad-playground/pico-sdk/src/rp2_common/hardware_uart/uart.c.obj
[ 26%] Building C object CMakeFiles/picopad-gb.dir/home/nils/picopad/picopad-playground/pico-sdk/src/rp2_common/hardware_clocks/clocks.c.obj
[ 27%] Building C object CMakeFiles/picopad-gb.dir/home/nils/picopad/picopad-playground/pico-sdk/src/rp2_common/hardware_pll/pll.c.obj
[ 28%] Building C object CMakeFiles/picopad-gb.dir/home/nils/picopad/picopad-playground/pico-sdk/src/rp2_common/hardware_vreg/vreg.c.obj
[ 29%] Building C object CMakeFiles/picopad-gb.dir/home/nils/picopad/picopad-playground/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.c.obj
[ 30%] Building C object CMakeFiles/picopad-gb.dir/home/nils/picopad/picopad-playground/pico-sdk/src/rp2_common/hardware_xosc/xosc.c.obj
[ 31%] Building ASM object CMakeFiles/picopad-gb.dir/home/nils/picopad/picopad-playground/pico-sdk/src/rp2_common/hardware_divider/divider.S.obj
[ 32%] Building C object CMakeFiles/picopad-gb.dir/home/nils/picopad/picopad-playground/pico-sdk/src/rp2_common/pico_runtime/runtime.c.obj
[ 34%] Building C object CMakeFiles/picopad-gb.dir/home/nils/picopad/picopad-playground/pico-sdk/src/rp2_common/pico_printf/printf.c.obj
[ 35%] Building ASM object CMakeFiles/picopad-gb.dir/home/nils/picopad/picopad-playground/pico-sdk/src/rp2_common/pico_bit_ops/bit_ops_aeabi.S.obj
[ 36%] Building C object CMakeFiles/picopad-gb.dir/home/nils/picopad/picopad-playground/pico-sdk/src/rp2_common/pico_bootrom/bootrom.c.obj
[ 37%] Building ASM object CMakeFiles/picopad-gb.dir/home/nils/picopad/picopad-playground/pico-sdk/src/rp2_common/pico_divider/divider.S.obj
[ 38%] Building ASM object CMakeFiles/picopad-gb.dir/home/nils/picopad/picopad-playground/pico-sdk/src/rp2_common/pico_double/double_aeabi.S.obj
[ 39%] Building C object CMakeFiles/picopad-gb.dir/home/nils/picopad/picopad-playground/pico-sdk/src/rp2_common/pico_double/double_init_rom.c.obj
[ 40%] Building C object CMakeFiles/picopad-gb.dir/home/nils/picopad/picopad-playground/pico-sdk/src/rp2_common/pico_double/double_math.c.obj
[ 41%] Building ASM object CMakeFiles/picopad-gb.dir/home/nils/picopad/picopad-playground/pico-sdk/src/rp2_common/pico_double/double_v1_rom_shim.S.obj
[ 42%] Building ASM object CMakeFiles/picopad-gb.dir/home/nils/picopad/picopad-playground/pico-sdk/src/rp2_common/pico_int64_ops/pico_int64_ops_aeabi.S.obj
[ 43%] Building ASM object CMakeFiles/picopad-gb.dir/home/nils/picopad/picopad-playground/pico-sdk/src/rp2_common/pico_float/float_aeabi.S.obj
[ 44%] Building C object CMakeFiles/picopad-gb.dir/home/nils/picopad/picopad-playground/pico-sdk/src/rp2_common/pico_float/float_init_rom.c.obj
[ 45%] Building C object CMakeFiles/picopad-gb.dir/home/nils/picopad/picopad-playground/pico-sdk/src/rp2_common/pico_float/float_math.c.obj
[ 46%] Building ASM object CMakeFiles/picopad-gb.dir/home/nils/picopad/picopad-playground/pico-sdk/src/rp2_common/pico_float/float_v1_rom_shim.S.obj
[ 47%] Building C object CMakeFiles/picopad-gb.dir/home/nils/picopad/picopad-playground/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.c.obj
[ 48%] Building ASM object CMakeFiles/picopad-gb.dir/home/nils/picopad/picopad-playground/pico-sdk/src/rp2_common/pico_mem_ops/mem_ops_aeabi.S.obj
[ 49%] Building ASM object CMakeFiles/picopad-gb.dir/home/nils/picopad/picopad-playground/pico-sdk/src/rp2_common/pico_standard_link/crt0.S.obj
[ 50%] Building CXX object CMakeFiles/picopad-gb.dir/home/nils/picopad/picopad-playground/pico-sdk/src/rp2_common/pico_standard_link/new_delete.cpp.obj
[ 51%] Building C object CMakeFiles/picopad-gb.dir/home/nils/picopad/picopad-playground/pico-sdk/src/rp2_common/pico_standard_link/binary_info.c.obj
[ 52%] Building C object CMakeFiles/picopad-gb.dir/home/nils/picopad/picopad-playground/pico-sdk/src/rp2_common/pico_stdio/stdio.c.obj
[ 53%] Building C object CMakeFiles/picopad-gb.dir/home/nils/picopad/picopad-playground/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.c.obj
[ 54%] Building C object CMakeFiles/picopad-gb.dir/home/nils/picopad/picopad-playground/pico-sdk/src/rp2_common/pico_multicore/multicore.c.obj
[ 55%] Building C object CMakeFiles/picopad-gb.dir/home/nils/picopad/picopad-playground/pico-sdk/src/rp2_common/hardware_spi/spi.c.obj
[ 56%] Building C object CMakeFiles/picopad-gb.dir/home/nils/picopad/picopad-playground/pico-sdk/src/rp2_common/pico_rand/rand.c.obj
[ 57%] Building C object CMakeFiles/picopad-gb.dir/home/nils/picopad/picopad-playground/pico-sdk/src/rp2_common/pico_unique_id/unique_id.c.obj
[ 58%] Building C object CMakeFiles/picopad-gb.dir/home/nils/picopad/picopad-playground/pico-sdk/src/rp2_common/hardware_flash/flash.c.obj
[ 59%] Building C object CMakeFiles/picopad-gb.dir/home/nils/picopad/picopad-playground/pico-sdk/src/rp2_common/hardware_dma/dma.c.obj
[ 60%] Building C object CMakeFiles/picopad-gb.dir/home/nils/picopad/picopad-playground/picopad-sdk/picopad-base/src/common/st7789/st7789.c.obj
[ 61%] Building C object CMakeFiles/picopad-gb.dir/home/nils/picopad/picopad-playground/picopad-sdk/picopad-base/src/common/sdk/sdk_adc.c.obj
[ 62%] Building C object CMakeFiles/picopad-gb.dir/home/nils/picopad/picopad-playground/picopad-sdk/picopad-base/src/common/sdk/sdk_watchdog.c.obj
[ 63%] Building C object CMakeFiles/picopad-gb.dir/home/nils/picopad/picopad-playground/picopad-sdk/picopad-base/src/common/sdk/sdk_flash.c.obj
[ 64%] Building C object CMakeFiles/picopad-gb.dir/home/nils/picopad/picopad-playground/picopad-sdk/picopad-base/src/common/sdk/sdk_config.c.obj
[ 65%] Building C object CMakeFiles/picopad-gb.dir/home/nils/picopad/picopad-playground/picopad-sdk/picopad-base/src/common/sdk/sdk_cpu.c.obj
[ 67%] Building C object CMakeFiles/picopad-gb.dir/home/nils/picopad/picopad-playground/pico-sdk/src/rp2_common/hardware_adc/adc.c.obj
[ 68%] Building C object CMakeFiles/picopad-gb.dir/home/nils/picopad/picopad-playground/picopad-sdk/picopad-base/src/common/libs/lib_calendar.c.obj
[ 69%] Building C object CMakeFiles/picopad-gb.dir/home/nils/picopad/picopad-playground/picopad-sdk/picopad-base/src/common/libs/lib_color.c.obj
[ 70%] Building C object CMakeFiles/picopad-gb.dir/home/nils/picopad/picopad-playground/picopad-sdk/picopad-base/src/common/libs/lib_crc.c.obj
[ 71%] Building C object CMakeFiles/picopad-gb.dir/home/nils/picopad/picopad-playground/picopad-sdk/picopad-base/src/common/libs/lib_decnum.c.obj
[ 72%] Building C object CMakeFiles/picopad-gb.dir/home/nils/picopad/picopad-playground/picopad-sdk/picopad-base/src/common/libs/lib_drawtft.c.obj
[ 73%] Building C object CMakeFiles/picopad-gb.dir/home/nils/picopad/picopad-playground/picopad-sdk/picopad-base/src/common/libs/lib_fat.c.obj
[ 74%] Building C object CMakeFiles/picopad-gb.dir/home/nils/picopad/picopad-playground/picopad-sdk/picopad-base/src/common/libs/lib_sd.c.obj
[ 75%] Building C object CMakeFiles/picopad-gb.dir/home/nils/picopad/picopad-playground/picopad-sdk/picopad-base/src/common/libs/lib_list.c.obj
[ 76%] Building C object CMakeFiles/picopad-gb.dir/home/nils/picopad/picopad-playground/picopad-sdk/picopad-base/src/common/libs/lib_print.c.obj
[ 77%] Building C object CMakeFiles/picopad-gb.dir/home/nils/picopad/picopad-playground/picopad-sdk/picopad-base/src/common/libs/lib_stream.c.obj
[ 78%] Building C object CMakeFiles/picopad-gb.dir/home/nils/picopad/picopad-playground/picopad-sdk/picopad-base/src/common/libs/lib_pwmsnd.c.obj
[ 79%] Building C object CMakeFiles/picopad-gb.dir/home/nils/picopad/picopad-playground/picopad-sdk/picopad-base/src/common/libs/lib_text.c.obj
[ 80%] Building C object CMakeFiles/picopad-gb.dir/home/nils/picopad/picopad-playground/picopad-sdk/picopad-base/src/common/libs/lib_textnum.c.obj
[ 81%] Building C object CMakeFiles/picopad-gb.dir/home/nils/picopad/picopad-playground/picopad-sdk/picopad-base/src/common/libs/lib_rand.c.obj
[ 82%] Building C object CMakeFiles/picopad-gb.dir/home/nils/picopad/picopad-playground/picopad-sdk/picopad-base/src/common/libs/lib_mat2d.c.obj
[ 83%] Building C object CMakeFiles/picopad-gb.dir/home/nils/picopad/picopad-playground/picopad-sdk/picopad-base/src/common/libs/lib_mem.c.obj
[ 84%] Building C object CMakeFiles/picopad-gb.dir/home/nils/picopad/picopad-playground/pico-sdk/src/rp2_common/cmsis/stub/CMSIS/Device/RaspberryPi/RP2040/Source/system_RP2040.c.obj
[ 85%] Building C object CMakeFiles/picopad-gb.dir/home/nils/picopad/picopad-playground/picopad-sdk/picopad-base/src/common/machine/picopad_bat.c.obj
[ 86%] Building C object CMakeFiles/picopad-gb.dir/home/nils/picopad/picopad-playground/picopad-sdk/picopad-base/src/common/machine/picopad_init.c.obj
[ 87%] Building C object CMakeFiles/picopad-gb.dir/home/nils/picopad/picopad-playground/picopad-sdk/picopad-base/src/common/machine/picopad_key.c.obj
[ 88%] Building C object CMakeFiles/picopad-gb.dir/home/nils/picopad/picopad-playground/picopad-sdk/picopad-base/src/common/machine/picopad_led.c.obj
[ 89%] Building C object CMakeFiles/picopad-gb.dir/home/nils/picopad/picopad-playground/picopad-sdk/picopad-base/src/common/machine/picopad_flash.c.obj
[ 90%] Building C object CMakeFiles/picopad-gb.dir/home/nils/picopad/picopad-playground/picopad-sdk/picopad-base/src/common/machine/picopad_pico_info.c.obj
[ 91%] Linking CXX executable picopad-gb.elf
Copying bin file to build directory
Copying assets to build directory
Error copying directory from "/home/nils/picopad/picopad-playground/picopad-sdk/picopad-gb/../assets/" to "/home/nils/picopad/picopad-playground/picopad-sdk/picopad-gb/../build/".
make[2]: *** [CMakeFiles/picopad-gb.dir/build.make:1421: picopad-gb.elf] Error 1
make[2]: *** Deleting file 'picopad-gb.elf'
make[1]: *** [CMakeFiles/Makefile2:1785: CMakeFiles/picopad-gb.dir/all] Error 2
make: *** [Makefile:91: all] Error 2


I still get soe error messages but I have now a pp2: 
nils@flunder:~/picopad/picopad-playground/picopad-sdk$ ls -l build/
total 100
-rwxrwxr-x 1 nils nils 101176 Jul 29 14:28 PICOPAD-GB.PP2

after adding a bpm and txt to the sd card I was able to play the game. the sound is not nice but it is working!!!!!

**Comment by tvecera** [comment]
Thank you very much for sharing your build experience. It's impressive that you managed to complete the build in the end. The issue is that I have several different programs in one repository. The dependencies listed are not needed for the GB emulator build, but they are included in the global CMakeList. I will attempt to remove them and only add them to the applications that actually require them to run.

**Comment by Gabbajoe** [comment]
Yeha I had no idea about and how cmake is working .. so I found out the issue I had was reading I did not do the submodule stuff and I looks like 2 submodule git repos would have failed anyways and need to be edited:
https://github.com/tvecera/picopad-playground/blob/main/.gitmodules

Issue: https://github.com/tvecera/picopad-playground/issues/2

**Comment by Gabbajoe** [comment]
created a pull request with changes to the [.gitmodules](https://github.com/tvecera/picopad-playground/blob/main/.gitmodules) file.
